/**
 * Cairn's data model and on-device library.
 *
 * A "plan" is one idea turned into a builder pack: a PRD, a user flow, a
 * milestone plan, and a reality check. The server writes the draft. The client
 * owns task identity and tracker state, so the AI can never claim work is
 * complete or invent a schedule.
 *
 * Plans live in localStorage. There is no account system: the library is per
 * device by design. An owner can explicitly publish a limited Track projection
 * to a protected team workspace; the private builder pack stays local.
 */

/** Exactly the form on screen 1. Only `idea` is required. */
export interface PlanInput {
  name: string
  idea: string
  targetUser?: string
  problem?: string
  goal?: string
}

/**
 * Product requirements. The three capped arrays are capped by the *server*
 * (a generation is clamped before it is returned), but the UI must not assume
 * the cap held — a hand-edited or older plan can carry more.
 */
export interface Prd {
  summary: string
  problem: string
  targetUser: string
  userGoal: string
  /** Max 5. */
  coreFeatures: string[]
  /** Max 5. */
  userStories: string[]
  /** Max 5. */
  successCriteria: string[]
  assumptions: string[]
  outOfScope: string[]
}

/**
 * One node of the user flow.
 *
 * `kind` is structural, not decorative: `FlowDiagram.vue` renders the branching
 * card off `kind === 'decision'` rather than guessing from the text, and the
 * generator is required to emit exactly one of those. It also means meaning is
 * never carried by colour alone, which is a scored accessibility requirement.
 */
export type FlowStepKind = 'entry' | 'action' | 'decision' | 'success' | 'exit'

export interface FlowBranch {
  label: string
  result: string
}

export interface FlowStep {
  kind: FlowStepKind
  title: string
  /** What the user does. */
  action: string
  /** What they should see happen. */
  result: string
  /** Present only when `kind === 'decision'`; exactly two outcomes. */
  branches?: [FlowBranch, FlowBranch]
}

export type TaskApprovalStatus = 'none' | 'pending' | 'approved' | 'changes_requested'

export interface Task {
  /** Client-authored stable identity. Never supplied by the model. */
  id: string
  text: string
  /** Local progress. Never supplied or changed by the model. */
  status: TaskStatus
  priority: TaskPriority
  labels: string[]
  notes: string
  dueDate?: string
  /** Task ids in this same plan. */
  dependsOn: string[]
  /** Wallet assigned by the team owner. */
  assignee?: string
  approvalStatus?: TaskApprovalStatus
  completionNote?: string
  reviewNote?: string
  /** Public proof of an owner-sent NIM reward for this completed task. */
  reward?: TaskReward
}

export interface TaskReward {
  recipient: string
  amountLuna: number
  transactionHash: string
  createdAt: number
}

export type TaskStatus = 'todo' | 'in_progress' | 'done'
export type TaskPriority = 'low' | 'medium' | 'high'

export interface Milestone {
  /** Client-authored stable identity. */
  id: string
  title: string
  outcome: string
  tasks: Task[]
  /** Dates are local calendar dates, never generated by the model. */
  startDate?: string
  dueDate?: string
  /** Owner supplied blocker flag. Task dependencies do not set this flag. */
  blocked: boolean
}

export interface BuildPlan {
  mvpScope: string[]
  milestones: Milestone[]
  risks: string[]
  acceptanceTests: string[]
  nextAction: string
}

export type ExperimentDecision = 'open' | 'continue' | 'change' | 'stop'
export type JournalKind = 'check_in' | 'task_started' | 'task_completed' | 'task_reopened' | 'experiment' | 'release'

export interface DailyCheckIn {
  id: string
  createdAt: number
  completed: string
  blocker: string
  changed: string
  nextStep: string
}

export interface BuildJournalEntry {
  id: string
  createdAt: number
  kind: JournalKind
  title: string
  detail?: string
  taskId?: string
}

export interface ValidationExperiment {
  id: string
  createdAt: number
  updatedAt: number
  hypothesis: string
  method: string
  successMetric: string
  result: string
  decision: ExperimentDecision
}

export interface ReleaseState {
  version: string
  audience: string
  knownIssues: string
  notes: string
  shippedAt?: number
}

export interface ExecutionState {
  focusTaskId?: string
  checkIns: DailyCheckIn[]
  journal: BuildJournalEntry[]
  experiments: ValidationExperiment[]
  release: ReleaseState
  /** Internal snapshot used to turn task status transitions into journal entries. */
  taskStates: Record<string, TaskStatus>
}

/** Fields that may leave an owner's device for a team or public share. */
export interface PublicTask {
  id: string
  text: string
  status: TaskStatus
  labels: string[]
  dueDate?: string
  assignee?: string
  approvalStatus?: TaskApprovalStatus
  completionNote?: string
  reviewNote?: string
  reward?: TaskReward
}

export interface PublicMilestone {
  id: string
  title: string
  outcome: string
  tasks: PublicTask[]
  startDate?: string
  dueDate?: string
  blocked: boolean
}

export interface PublicBuildPlan {
  mvpScope: string[]
  milestones: PublicMilestone[]
  risks: string[]
  acceptanceTests: string[]
  nextAction: string
}

/**
 * Server-authored build task shape.
 *
 * A new plan uses plain text tasks. A refinement may include an existing task's
 * id when it renames or moves that task. The client still owns all progress and
 * tracker metadata.
 */
export interface BuildTaskDraft {
  id?: string
  text: string
}

export interface BuildMilestoneDraft {
  title: string
  outcome: string
  tasks: Array<string | BuildTaskDraft>
}

export interface BuildPlanDraft {
  mvpScope: string[]
  milestones: BuildMilestoneDraft[]
  risks: string[]
  acceptanceTests: string[]
  nextAction: string
}

export type RealityPriority = 'high' | 'medium' | 'low'

export interface RealityCheckItem {
  priority: RealityPriority
  concern: string
  why: string
  fix: string
}

export interface BuildPlanChanges {
  mvpScope?: string[]
  milestones?: BuildMilestoneDraft[]
  risks?: string[]
  acceptanceTests?: string[]
  nextAction?: string
}

/** A targeted refinement. Missing fields must remain untouched. */
export interface PlanChanges {
  prd?: Partial<Prd>
  flow?: FlowStep[]
  build?: BuildPlanChanges
  realityCheck?: RealityCheckItem[]
}

export interface Plan {
  id: string
  /** Display name. May be empty — use `titleOf()` rather than reading this raw. */
  name: string
  createdAt: number
  updatedAt: number
  /**
   * The form as submitted, kept verbatim. Two reasons: "Try again" after a
   * failed generation must never lose the user's typing, and regenerating a
   * saved plan should start from what they actually wrote.
   */
  input: PlanInput
  prd: Prd
  flow: FlowStep[]
  build: BuildPlan
  realityCheck: RealityCheckItem[]
  execution: ExecutionState
  /** Set once the plan has been shared. Absent means it has never left the device. */
  shareId?: string
  /** Set when the owner creates a protected team workspace. */
  teamId?: string
}

/** Steps outside this range are a generator bug; the UI still renders them. */
export const FLOW_MIN_STEPS = 5
export const FLOW_MAX_STEPS = 8
/** Applies to coreFeatures, userStories and successCriteria. */
export const PRD_LIST_MAX = 5
export const BUILD_SCOPE_MIN = 3
export const BUILD_SCOPE_MAX = 5
export const BUILD_MILESTONE_COUNT = 3
export const BUILD_TASK_MIN = 8
export const BUILD_TASK_MAX = 12
export const BUILD_LIST_MAX = 5
export const REALITY_CHECK_COUNT = 3
export const TRACKER_LABEL_MAX = 3
export const TRACKER_LABEL_LENGTH = 24
export const TRACKER_NOTES_MAX = 1000
export const TRACKER_DEPENDENCY_MAX = 4
export const TRACKER_MILESTONE_MAX = 12
export const EXECUTION_HISTORY_MAX = 100
export const EXECUTION_EXPERIMENT_MAX = 20

// -- identity ---------------------------------------------------------------

/**
 * `crypto.randomUUID()` requires a secure context, and LAN HTTP — how this app
 * is tested on a real handset — is not one. Feature-detect, then fall back to
 * `getRandomValues`, then to `Math.random`. Collisions only matter within one
 * device's library, so the weakest tier is still fine.
 */
export function newId(): string {
  const c: Crypto | undefined = typeof crypto !== 'undefined' ? crypto : undefined

  if (typeof c?.randomUUID === 'function') {
    try {
      return c.randomUUID()
    } catch {
      /* fall through */
    }
  }

  if (typeof c?.getRandomValues === 'function') {
    const bytes = c.getRandomValues(new Uint8Array(16))
    return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('')
  }

  return `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 10)}`
}

/** Task ids are local opaque identifiers, never executable input. */
export function isValidTaskId(value: unknown): value is string {
  return typeof value === 'string' && /^[A-Za-z0-9][A-Za-z0-9_-]{0,95}$/.test(value)
}

export function emptyBuildPlan(): BuildPlan {
  return {
    mvpScope: [],
    milestones: [],
    risks: [],
    acceptanceTests: [],
    nextAction: '',
  }
}

export function emptyExecutionState(build?: BuildPlan): ExecutionState {
  const taskStates: Record<string, TaskStatus> = {}
  for (const task of build?.milestones.flatMap((milestone) => milestone.tasks) ?? []) {
    taskStates[task.id] = task.status
  }
  return {
    checkIns: [],
    journal: [],
    experiments: [],
    release: { version: '0.1.0', audience: '', knownIssues: '', notes: '' },
    taskStates,
  }
}

function validStatus(value: unknown): value is TaskStatus {
  return value === 'todo' || value === 'in_progress' || value === 'done'
}

function validPriority(value: unknown): value is TaskPriority {
  return value === 'low' || value === 'medium' || value === 'high'
}

/** Calendar dates are deliberately strict so lexical comparisons are safe. */
export function isValidDate(value: unknown): value is string {
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false
  const [year, month, day] = value.split('-').map(Number)
  if (!year || !month || !day) return false
  const date = new Date(Date.UTC(year, month - 1, day))
  return date.getUTCFullYear() === year && date.getUTCMonth() === month - 1 && date.getUTCDate() === day
}

function optionalDate(value: unknown): string | undefined {
  return isValidDate(value) ? value : undefined
}

function labels(value: unknown): string[] {
  if (!Array.isArray(value)) return []
  const result: string[] = []
  for (const item of value) {
    if (typeof item !== 'string') continue
    const label = item.replace(/\s+/g, ' ').trim().slice(0, TRACKER_LABEL_LENGTH)
    if (!label || result.includes(label)) continue
    result.push(label)
    if (result.length >= TRACKER_LABEL_MAX) break
  }
  return result
}

function dependencies(value: unknown): string[] {
  if (!Array.isArray(value)) return []
  const result: string[] = []
  for (const item of value) {
    if (typeof item !== 'string' || !item || result.includes(item)) continue
    result.push(item)
    if (result.length >= TRACKER_DEPENDENCY_MAX) break
  }
  return result
}

function normalizeTask(task: unknown): Task | null {
  if (typeof task !== 'object' || task === null) return null
  const raw = task as Record<string, unknown>
  if (typeof raw.text !== 'string') return null
  const text = raw.text.replace(/\s+/g, ' ').trim().slice(0, 260)
  if (!text) return null
  const status = validStatus(raw.status) ? raw.status : raw.done === true ? 'done' : 'todo'
  const notes = typeof raw.notes === 'string' ? raw.notes.slice(0, TRACKER_NOTES_MAX) : ''
  const reward = normalizeReward(raw.reward)
  const assignee = typeof raw.assignee === 'string' ? raw.assignee.replace(/\s+/g, '').toUpperCase() : ''
  const approvalStatus = raw.approvalStatus === 'pending' || raw.approvalStatus === 'approved' || raw.approvalStatus === 'changes_requested'
    ? raw.approvalStatus
    : 'none'
  const completionNote = typeof raw.completionNote === 'string' ? raw.completionNote.trim().slice(0, 500) : ''
  const reviewNote = typeof raw.reviewNote === 'string' ? raw.reviewNote.trim().slice(0, 500) : ''
  return {
    id: typeof raw.id === 'string' && raw.id ? raw.id : newId(),
    text,
    status,
    priority: validPriority(raw.priority) ? raw.priority : 'medium',
    labels: labels(raw.labels),
    notes,
    ...(optionalDate(raw.dueDate) ? { dueDate: raw.dueDate as string } : {}),
    dependsOn: dependencies(raw.dependsOn),
    ...(/^NQ[0-9A-Z]{34}$/.test(assignee) ? { assignee } : {}),
    ...(approvalStatus !== 'none' ? { approvalStatus } : {}),
    ...(completionNote ? { completionNote } : {}),
    ...(reviewNote ? { reviewNote } : {}),
    ...(reward ? { reward } : {}),
  }
}

function normalizeReward(value: unknown): TaskReward | null {
  if (typeof value !== 'object' || value === null) return null
  const raw = value as Record<string, unknown>
  const recipient = typeof raw.recipient === 'string' ? raw.recipient.replace(/\s+/g, '').toUpperCase() : ''
  const transactionHash = typeof raw.transactionHash === 'string' ? raw.transactionHash.toLowerCase() : ''
  if (!/^NQ[0-9A-Z]{34}$/.test(recipient) || !/^[0-9a-f]{64}$/.test(transactionHash)) return null
  if (typeof raw.amountLuna !== 'number' || !Number.isSafeInteger(raw.amountLuna) || raw.amountLuna < 1) return null
  if (typeof raw.createdAt !== 'number' || !Number.isFinite(raw.createdAt)) return null
  return { recipient, amountLuna: raw.amountLuna, transactionHash, createdAt: raw.createdAt }
}

function sanitizeBuildDependencies(milestones: Milestone[]): void {
  const tasks = milestones.flatMap((milestone) => milestone.tasks)
  const byId = new Map(tasks.map((task) => [task.id, task]))
  for (const task of tasks) {
    const accepted: string[] = []
    for (const dependency of task.dependsOn) {
      if (dependency === task.id || !byId.has(dependency)) continue
      const graph = new Map<string, string[]>()
      for (const candidate of tasks) {
        graph.set(candidate.id, candidate.id === task.id ? [...accepted, dependency] : candidate.dependsOn)
      }
      if (hasDependencyCycle(graph)) continue
      accepted.push(dependency)
      if (accepted.length >= TRACKER_DEPENDENCY_MAX) break
    }
    task.dependsOn = accepted
  }
}

function normalizeMatch(value: string): string {
  return value.trim().replace(/\s+/g, ' ').toLocaleLowerCase()
}

function draftTaskText(value: string | BuildTaskDraft): string {
  const text = typeof value === 'string' ? value : value.text
  return typeof text === 'string' ? text.trim() : ''
}

function draftTaskId(value: string | BuildTaskDraft): string | undefined {
  return typeof value === 'object' && value !== null ? value.id : undefined
}

/**
 * Validate explicit refinement references before the planner is materialized.
 * Unknown or duplicate ids are rejected instead of silently creating a new task
 * and losing the old task's progress.
 */
export function validateTaskReferences(
  previous: BuildPlan | undefined,
  milestones: BuildMilestoneDraft[],
): void {
  const existing = new Set((previous?.milestones ?? []).flatMap((milestone) => milestone.tasks.map((task) => task.id)))
  const seen = new Set<string>()
  for (const milestone of milestones) {
    for (const entry of milestone.tasks) {
      const id = draftTaskId(entry)
      if (id === undefined) continue
      if (!isValidTaskId(id) || !existing.has(id)) {
        throw new Error('The refinement referenced an unknown task.')
      }
      if (seen.has(id)) throw new Error('The refinement referenced the same task more than once.')
      seen.add(id)
    }
  }
}

/**
 * Turn a server draft into client-owned work state.
 *
 * Matching happens across the whole prior plan, not only inside the same
 * milestone. A useful refinement may move a task without erasing its progress.
 */
export function materializeBuildPlan(
  draft: BuildPlanDraft,
  previous?: BuildPlan,
): BuildPlan {
  validateTaskReferences(previous, draft.milestones)

  const oldTasks = new Map<string, Task[]>()
  for (const milestone of previous?.milestones ?? []) {
    for (const task of milestone.tasks) {
      const key = normalizeMatch(task.text)
      const bucket = oldTasks.get(key) ?? []
      bucket.push(task)
      oldTasks.set(key, bucket)
    }
  }

  const oldMilestones = new Map<string, Milestone[]>()
  for (const milestone of previous?.milestones ?? []) {
    const key = normalizeMatch(milestone.title)
    const bucket = oldMilestones.get(key) ?? []
    bucket.push(milestone)
    oldMilestones.set(key, bucket)
  }

  const oldById = new Map<string, Task>()
  for (const milestone of previous?.milestones ?? []) {
    for (const task of milestone.tasks) oldById.set(task.id, task)
  }

  const usedTasks = new Set<string>()
  const usedMilestones = new Set<string>()

  const result: BuildPlan = {
    mvpScope: draft.mvpScope.map((item) => item.trim()).filter(Boolean),
    milestones: draft.milestones.map((item) => {
      const milestoneMatch = (oldMilestones.get(normalizeMatch(item.title)) ?? []).find(
        (candidate) => !usedMilestones.has(candidate.id),
      )
      const id = milestoneMatch?.id ?? newId()
      usedMilestones.add(id)

      return {
        id,
        title: item.title.trim(),
        outcome: item.outcome.trim(),
        ...(milestoneMatch?.startDate ? { startDate: milestoneMatch.startDate } : {}),
        ...(milestoneMatch?.dueDate ? { dueDate: milestoneMatch.dueDate } : {}),
        blocked: milestoneMatch?.blocked === true,
        tasks: item.tasks
          .map((entry) => ({ entry, text: draftTaskText(entry) }))
          .filter(({ text }) => Boolean(text))
          .filter(Boolean)
          .map(({ entry, text }, taskIndex, draftTasks) => {
            const explicitId = draftTaskId(entry)
            const explicit = explicitId ? oldById.get(explicitId) : undefined
            if (explicit && usedTasks.has(explicit.id)) {
              throw new Error('The refinement referenced the same task more than once.')
            }
            const exact = explicit ?? (oldTasks.get(normalizeMatch(text)) ?? []).find(
              (candidate) => !usedTasks.has(candidate.id),
            )
            // When a refinement keeps the milestone and task count, its task
            // positions are stable identity hints. This preserves status,
            // notes, dates, and dependencies when the model merely renames a
            // task, while avoiding positional guesses for insertions/deletions.
            const positional = milestoneMatch && draftTasks.length === milestoneMatch.tasks.length
              ? milestoneMatch.tasks[taskIndex]
              : undefined
            const match = exact ?? (
              positional
                && positional.status !== 'done'
                && !usedTasks.has(positional.id)
                ? positional
                : undefined
            )
            if (match) {
              usedTasks.add(match.id)
              const previousStatus = validStatus(match.status)
                ? match.status
                : (match as Task & { done?: boolean }).done === true ? 'done' : 'todo'
              return {
                id: match.id,
                text,
                status: previousStatus,
                priority: validPriority(match.priority) ? match.priority : 'medium',
                labels: labels(match.labels),
                notes: typeof match.notes === 'string' ? match.notes.slice(0, TRACKER_NOTES_MAX) : '',
                ...(match.dueDate ? { dueDate: match.dueDate } : {}),
                dependsOn: [],
              }
            }
            return {
              id: newId(),
              text,
              status: 'todo',
              priority: 'medium',
              labels: [],
              notes: '',
              dependsOn: [],
            }
          }),
      }
    }),
    risks: draft.risks.map((item) => item.trim()).filter(Boolean),
    acceptanceTests: draft.acceptanceTests.map((item) => item.trim()).filter(Boolean),
    nextAction: draft.nextAction.trim(),
  }

  // A refinement can move a task between milestones. Preserve dependency links
  // only when both endpoints survived. Any link that would create a cycle is
  // dropped rather than making the tracker impossible to edit.
  const nextById = new Map<string, Task>()
  for (const milestone of result.milestones) {
    for (const task of milestone.tasks) nextById.set(task.id, task)
  }

  for (const task of nextById.values()) {
    const old = oldById.get(task.id)
    if (!old) continue
    const candidates = old.dependsOn.filter((id) => nextById.has(id) && id !== task.id)
    const accepted: string[] = []
    for (const dependency of candidates) {
      const adjacency = new Map<string, string[]>()
      for (const candidate of nextById.values()) {
        adjacency.set(candidate.id, candidate.id === task.id ? accepted : candidate.dependsOn)
      }
      adjacency.set(task.id, [...accepted, dependency])
      if (hasDependencyCycle(adjacency)) continue
      accepted.push(dependency)
    }
    task.dependsOn = accepted.slice(0, TRACKER_DEPENDENCY_MAX)
  }

  return result
}

function hasDependencyCycle(graph: Map<string, string[]>): boolean {
  const visiting = new Set<string>()
  const visited = new Set<string>()

  function visit(id: string): boolean {
    if (visiting.has(id)) return true
    if (visited.has(id)) return false
    visiting.add(id)
    for (const dependency of graph.get(id) ?? []) {
      if (graph.has(dependency) && visit(dependency)) return true
    }
    visiting.delete(id)
    visited.add(id)
    return false
  }

  for (const id of graph.keys()) {
    if (visit(id)) return true
  }
  return false
}

// -- derived display values -------------------------------------------------

/** The name if there is one, otherwise the opening of the idea. Never empty. */
export function titleOf(plan: Pick<Plan, 'name' | 'input'>): string {
  const name = plan.name.trim()
  if (name) return name

  const idea = plan.input.idea.trim().replace(/\s+/g, ' ')
  if (!idea) return 'Untitled plan'
  return idea.length > 48 ? `${idea.slice(0, 47)}…` : idea
}

/** `{project-name}-plan.md` — the filename the spec asks for. */
export function slugOf(plan: Pick<Plan, 'name' | 'input'>): string {
  const slug = titleOf(plan)
    .toLowerCase()
    .normalize('NFKD')
    // Drop the combining marks NFKD just split off, so "café" slugs as "cafe".
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)
  return slug || 'untitled'
}

/**
 * "just now" / "4 minutes ago" for the library list.
 *
 * `Intl.RelativeTimeFormat` is missing in some older WebViews, so it is
 * feature-detected with an English fallback rather than assumed.
 */
export function relativeTime(timestamp: number, now = Date.now()): string {
  const seconds = Math.round((timestamp - now) / 1000)
  const magnitude = Math.abs(seconds)

  if (magnitude < 45) return 'just now'

  const units: [Intl.RelativeTimeFormatUnit, number][] = [
    ['year', 31_536_000],
    ['month', 2_592_000],
    ['week', 604_800],
    ['day', 86_400],
    ['hour', 3600],
    ['minute', 60],
  ]

  for (const [unit, size] of units) {
    if (magnitude < size) continue
    const amount = Math.round(seconds / size)

    if (typeof Intl !== 'undefined' && typeof Intl.RelativeTimeFormat === 'function') {
      try {
        return new Intl.RelativeTimeFormat(undefined, { numeric: 'auto' }).format(amount, unit)
      } catch {
        /* fall through to English */
      }
    }

    const n = Math.abs(amount)
    const plural = n === 1 ? unit : `${unit}s`
    return amount < 0 ? `${n} ${plural} ago` : `in ${n} ${plural}`
  }

  return 'just now'
}

// -- the library ------------------------------------------------------------

const STORAGE_KEY = 'cairn.library.v3'
const LEGACY_STORAGE_KEY = 'cairn.library.v2'
const OLDER_STORAGE_KEY = 'cairn.library.v1'

interface StoredLibrary {
  version: 3
  plans: Plan[]
}

/** `structuredClone` is missing in older WebViews; JSON covers this shape. */
function clone<T>(value: T): T {
  if (typeof structuredClone === 'function') {
    try {
      return structuredClone(value)
    } catch {
      // Vue reactive proxies and older embedded WebViews can reject cloning.
      // Plans are JSON-shaped, so the fallback is safe for this storage layer.
    }
  }
  return JSON.parse(JSON.stringify(value)) as T
}

function normalizeRealityCheck(value: unknown): RealityCheckItem[] {
  if (!Array.isArray(value)) return []
  const priorities: RealityPriority[] = ['high', 'medium', 'low']

  return value.flatMap((item) => {
    if (typeof item !== 'object' || item === null) return []
    const raw = item as Partial<RealityCheckItem>
    if (
      typeof raw.concern !== 'string' ||
      typeof raw.why !== 'string' ||
      typeof raw.fix !== 'string'
    ) return []
    const priority = priorities.includes(raw.priority as RealityPriority)
      ? (raw.priority as RealityPriority)
      : 'medium'
    return [{ priority, concern: raw.concern, why: raw.why, fix: raw.fix }]
  })
}

function normalizeBuild(value: unknown): BuildPlan {
  if (typeof value !== 'object' || value === null) return emptyBuildPlan()
  const raw = value as Record<string, unknown>
  if (!Array.isArray(raw.milestones)) return emptyBuildPlan()

  const milestones = raw.milestones.slice(0, TRACKER_MILESTONE_MAX).flatMap((item) => {
    if (typeof item !== 'object' || item === null) return []
    const record = item as Record<string, unknown>
    const tasks = Array.isArray(record.tasks)
      ? record.tasks.flatMap((task) => {
        const normalized = normalizeTask(task)
        return normalized ? [normalized] : []
      })
      : []
    const startDate = optionalDate(record.startDate)
    const dueDate = optionalDate(record.dueDate)
    const milestone = {
      id: typeof record.id === 'string' && record.id ? record.id : newId(),
      title: typeof record.title === 'string' ? record.title.slice(0, 100) : '',
      outcome: typeof record.outcome === 'string' ? record.outcome.slice(0, 260) : '',
      ...(startDate ? { startDate } : {}),
      ...(dueDate ? { dueDate } : {}),
      blocked: record.blocked === true,
      tasks,
    }
    if (milestone.startDate && milestone.dueDate && milestone.startDate > milestone.dueDate) {
      delete milestone.dueDate
    }
    return [milestone]
  })

  sanitizeBuildDependencies(milestones)

  return {
    mvpScope: Array.isArray(raw.mvpScope)
      ? raw.mvpScope.filter((item): item is string => typeof item === 'string').map((item) => item.trim())
      : [],
    milestones,
    risks: Array.isArray(raw.risks)
      ? raw.risks.filter((item): item is string => typeof item === 'string').map((item) => item.trim())
      : [],
    acceptanceTests: Array.isArray(raw.acceptanceTests)
      ? raw.acceptanceTests.filter((item): item is string => typeof item === 'string').map((item) => item.trim())
      : [],
    nextAction: typeof raw.nextAction === 'string' ? raw.nextAction : '',
  }
}

/**
 * Create the only build shape allowed to cross a team boundary.
 *
 * The server applies its own clamp and rebuilds public ids. This client helper
 * is still useful because it makes the privacy boundary explicit before a
 * request is made.
 */
export function publicBuildOf(build: BuildPlan): PublicBuildPlan {
  return {
    mvpScope: build.mvpScope.slice(0, BUILD_SCOPE_MAX),
    milestones: build.milestones.slice(0, TRACKER_MILESTONE_MAX).map((milestone) => ({
      id: milestone.id,
      title: milestone.title,
      outcome: milestone.outcome,
      tasks: milestone.tasks.map((task) => ({
        id: task.id,
        text: task.text,
        status: task.status,
        labels: task.labels.slice(0, TRACKER_LABEL_MAX),
        ...(task.dueDate ? { dueDate: task.dueDate } : {}),
        ...(task.assignee ? { assignee: task.assignee } : {}),
        ...(task.approvalStatus ? { approvalStatus: task.approvalStatus } : {}),
        ...(task.completionNote ? { completionNote: task.completionNote } : {}),
        ...(task.reviewNote ? { reviewNote: task.reviewNote } : {}),
        ...(task.reward ? { reward: { ...task.reward } } : {}),
      })),
      ...(milestone.startDate ? { startDate: milestone.startDate } : {}),
      ...(milestone.dueDate ? { dueDate: milestone.dueDate } : {}),
      blocked: milestone.blocked,
    })),
    risks: build.risks.slice(0, BUILD_LIST_MAX),
    acceptanceTests: build.acceptanceTests.slice(0, BUILD_LIST_MAX),
    nextAction: build.nextAction,
  }
}

/**
 * Create the narrower projection used by protected teams.
 *
 * A team member needs the Track board only. The builder pack summary can
 * contain product decisions that the owner did not intend to publish, so it
 * is excluded before the request reaches the Worker as well as at the Worker
 * boundary.
 */
export function publicTrackOf(build: BuildPlan): PublicBuildPlan {
  const projection = publicBuildOf(build)
  return {
    ...projection,
    mvpScope: [],
    risks: [],
    acceptanceTests: [],
    nextAction: '',
  }
}

/** Hydrate a server public projection with safe private defaults for the UI. */
export function hydratePublicBuild(value: unknown): BuildPlan {
  return normalizeBuild(value)
}

function cleanExecutionText(value: unknown, max = 600): string {
  return typeof value === 'string' ? value.trim().slice(0, max) : ''
}

function normalizeExecution(value: unknown, build: BuildPlan): ExecutionState {
  const fallback = emptyExecutionState(build)
  if (typeof value !== 'object' || value === null) return fallback
  const raw = value as Record<string, unknown>
  const validKinds: JournalKind[] = ['check_in', 'task_started', 'task_completed', 'task_reopened', 'experiment', 'release']
  const validDecisions: ExperimentDecision[] = ['open', 'continue', 'change', 'stop']
  const taskIds = new Set(build.milestones.flatMap((milestone) => milestone.tasks.map((task) => task.id)))

  const checkIns: DailyCheckIn[] = Array.isArray(raw.checkIns)
    ? raw.checkIns.slice(-EXECUTION_HISTORY_MAX).flatMap((item) => {
      if (typeof item !== 'object' || item === null) return []
      const entry = item as Record<string, unknown>
      if (typeof entry.createdAt !== 'number' || !Number.isFinite(entry.createdAt)) return []
      return [{
        id: typeof entry.id === 'string' && entry.id ? entry.id : newId(),
        createdAt: entry.createdAt,
        completed: cleanExecutionText(entry.completed),
        blocker: cleanExecutionText(entry.blocker),
        changed: cleanExecutionText(entry.changed),
        nextStep: cleanExecutionText(entry.nextStep),
      }]
    })
    : []

  const journal: BuildJournalEntry[] = Array.isArray(raw.journal)
    ? raw.journal.slice(-EXECUTION_HISTORY_MAX).flatMap((item) => {
      if (typeof item !== 'object' || item === null) return []
      const entry = item as Record<string, unknown>
      const kind = validKinds.includes(entry.kind as JournalKind) ? entry.kind as JournalKind : null
      const title = cleanExecutionText(entry.title, 180)
      if (!kind || !title || typeof entry.createdAt !== 'number' || !Number.isFinite(entry.createdAt)) return []
      const detail = cleanExecutionText(entry.detail)
      const taskId = typeof entry.taskId === 'string' && taskIds.has(entry.taskId) ? entry.taskId : undefined
      return [{ id: typeof entry.id === 'string' && entry.id ? entry.id : newId(), createdAt: entry.createdAt, kind, title, ...(detail ? { detail } : {}), ...(taskId ? { taskId } : {}) }]
    })
    : []

  const experiments: ValidationExperiment[] = Array.isArray(raw.experiments)
    ? raw.experiments.slice(-EXECUTION_EXPERIMENT_MAX).flatMap((item) => {
      if (typeof item !== 'object' || item === null) return []
      const entry = item as Record<string, unknown>
      const hypothesis = cleanExecutionText(entry.hypothesis)
      if (!hypothesis) return []
      const createdAt = typeof entry.createdAt === 'number' && Number.isFinite(entry.createdAt) ? entry.createdAt : Date.now()
      const updatedAt = typeof entry.updatedAt === 'number' && Number.isFinite(entry.updatedAt) ? entry.updatedAt : createdAt
      return [{
        id: typeof entry.id === 'string' && entry.id ? entry.id : newId(),
        createdAt,
        updatedAt,
        hypothesis,
        method: cleanExecutionText(entry.method),
        successMetric: cleanExecutionText(entry.successMetric),
        result: cleanExecutionText(entry.result),
        decision: validDecisions.includes(entry.decision as ExperimentDecision) ? entry.decision as ExperimentDecision : 'open',
      }]
    })
    : []

  const releaseRaw = typeof raw.release === 'object' && raw.release !== null ? raw.release as Record<string, unknown> : {}
  const taskStates: Record<string, TaskStatus> = {}
  const storedStates = typeof raw.taskStates === 'object' && raw.taskStates !== null ? raw.taskStates as Record<string, unknown> : {}
  for (const task of build.milestones.flatMap((milestone) => milestone.tasks)) {
    taskStates[task.id] = validStatus(storedStates[task.id]) ? storedStates[task.id] as TaskStatus : task.status
  }

  const focusTaskId = typeof raw.focusTaskId === 'string' && taskIds.has(raw.focusTaskId) ? raw.focusTaskId : undefined
  return {
    ...(focusTaskId ? { focusTaskId } : {}),
    checkIns,
    journal,
    experiments,
    release: {
      version: cleanExecutionText(releaseRaw.version, 30) || '0.1.0',
      audience: cleanExecutionText(releaseRaw.audience, 300),
      knownIssues: cleanExecutionText(releaseRaw.knownIssues, 1200),
      notes: cleanExecutionText(releaseRaw.notes, 2000),
      ...(typeof releaseRaw.shippedAt === 'number' && Number.isFinite(releaseRaw.shippedAt) ? { shippedAt: releaseRaw.shippedAt } : {}),
    },
    taskStates,
  }
}

export function syncTaskJournal(plan: Plan, now = Date.now()): void {
  const execution = plan.execution ?? emptyExecutionState(plan.build)
  const currentTasks = plan.build.milestones.flatMap((milestone) => milestone.tasks)
  const nextStates: Record<string, TaskStatus> = {}
  for (const task of currentTasks) {
    nextStates[task.id] = task.status
    const previous = execution.taskStates[task.id]
    if (!previous || previous === task.status) continue
    const kind: JournalKind = task.status === 'done' ? 'task_completed' : task.status === 'in_progress' ? 'task_started' : 'task_reopened'
    execution.journal.push({ id: newId(), createdAt: now, kind, title: task.text, taskId: task.id })
  }
  execution.taskStates = nextStates
  execution.journal = execution.journal.slice(-EXECUTION_HISTORY_MAX)
  plan.execution = execution
}

function normalizePlan(value: unknown): Plan | null {
  if (typeof value !== 'object' || value === null) return null
  const plan = value as Partial<Plan>
  if (!(
    typeof plan.id === 'string' &&
    typeof plan.createdAt === 'number' &&
    typeof plan.updatedAt === 'number' &&
    typeof plan.input === 'object' &&
    plan.input !== null &&
    typeof plan.prd === 'object' &&
    plan.prd !== null &&
    Array.isArray(plan.flow)
  )) return null

  const copied = clone(value) as Omit<Plan, 'build' | 'realityCheck'>
  const { teamId, ...withoutTeamId } = copied
  const safeTeamId = typeof teamId === 'string' && /^[a-z2-9]{16,32}$/i.test(teamId) ? teamId : undefined

  const build = normalizeBuild(plan.build)
  return {
    ...withoutTeamId,
    ...(safeTeamId ? { teamId: safeTeamId } : {}),
    build,
    realityCheck: normalizeRealityCheck(plan.realityCheck),
    execution: normalizeExecution(plan.execution, build),
  }
}

/** Normalize a public share snapshot before rendering it beside local plans. */
export function normalizeSharedPlan(value: unknown): Plan | null {
  return normalizePlan(value)
}

export interface PlanBackup {
  format: 'cairn-plan'
  version: 1
  exportedAt: number
  plan: Plan
}

/** A portable, versioned copy of one route. */
export function exportPlanBackup(plan: Plan): PlanBackup {
  return { format: 'cairn-plan', version: 1, exportedAt: Date.now(), plan: clone(plan) }
}

/** Restore a backup as a new local route, without inheriting server access. */
export function importPlanBackup(text: string): Plan | null {
  try {
    const parsed: unknown = JSON.parse(text)
    const candidate = typeof parsed === 'object' && parsed !== null &&
      (parsed as { format?: unknown }).format === 'cairn-plan'
      ? (parsed as { plan?: unknown }).plan
      : parsed
    const normalized = normalizePlan(candidate)
    if (!normalized) return null
    const now = Date.now()
    const { shareId: _shareId, teamId: _teamId, ...local } = normalized
    return { ...local, id: newId(), createdAt: now, updatedAt: now }
  } catch {
    return null
  }
}

/**
 * Read the whole library. Anything unparseable is dropped rather than thrown —
 * a corrupted entry must not take out the app, and a private-mode WebView can
 * throw on localStorage access at all.
 */
function read(): Plan[] {
  try {
    const current = localStorage.getItem(STORAGE_KEY)
    const legacy = current ? null : localStorage.getItem(LEGACY_STORAGE_KEY)
    const oldest = current || legacy ? null : localStorage.getItem(OLDER_STORAGE_KEY)
    const raw = current ?? legacy ?? oldest
    if (!raw) return []
    const parsed: unknown = JSON.parse(raw)
    const plans = (parsed as { plans?: unknown })?.plans
    if (!Array.isArray(plans)) return []
    const normalized = plans.flatMap((plan) => {
      const valid = normalizePlan(plan)
      return valid ? [valid] : []
    })

    // Migration is additive. Keep older keys until this v3 write succeeds, so a
    // storage failure cannot destroy the only copy of the user's work.
    if (!current && normalized.length) write(normalized)
    return normalized
  } catch {
    return []
  }
}

/** Returns false when the write failed, so callers can warn instead of lying. */
function write(plans: Plan[]): boolean {
  try {
    const payload: StoredLibrary = { version: 3, plans }
    localStorage.setItem(STORAGE_KEY, JSON.stringify(payload))
    return true
  } catch {
    return false
  }
}

/** Most recently edited first — the order the library screen shows them in. */
export function listPlans(): Plan[] {
  return read().sort((a, b) => b.updatedAt - a.updatedAt)
}

export function getPlan(id: string): Plan | null {
  return read().find((plan) => plan.id === id) ?? null
}

export function createPlan(
  input: PlanInput,
  prd: Prd,
  flow: FlowStep[],
  buildDraft: BuildPlanDraft = {
    mvpScope: [],
    milestones: [],
    risks: [],
    acceptanceTests: [],
    nextAction: '',
  },
  realityCheck: RealityCheckItem[] = [],
): Plan {
  const now = Date.now()
  const build = materializeBuildPlan(buildDraft)
  return {
    id: newId(),
    name: input.name.trim(),
    createdAt: now,
    updatedAt: now,
    input: clone(input),
    prd: clone(prd),
    flow: clone(flow),
    build,
    realityCheck: clone(realityCheck),
    execution: emptyExecutionState(build),
  }
}

/**
 * Insert or replace, stamping `updatedAt`. Returns false if persistence failed
 * — the caller keeps the plan in memory either way, so the session continues.
 */
export function savePlan(plan: Plan): boolean {
  const copyOfPlan = clone(plan)
  // Normalize at the write boundary as well as on read. Editors validate their
  // own fields, but this keeps programmatic callers from storing invalid dates,
  // stale done flags, unknown dependencies, or overlong tracker values.
  const normalizedBuild = normalizeBuild(copyOfPlan.build)
  const stamped: Plan = {
    ...copyOfPlan,
    build: normalizedBuild,
    execution: normalizeExecution(copyOfPlan.execution, normalizedBuild),
    updatedAt: Date.now(),
  }
  const plans = read()
  const index = plans.findIndex((existing) => existing.id === stamped.id)

  if (index === -1) plans.push(stamped)
  else plans[index] = stamped

  return write(plans)
}

export function renamePlan(id: string, name: string): Plan | null {
  const plans = read()
  const plan = plans.find((existing) => existing.id === id)
  if (!plan) return null

  plan.name = name.trim()
  plan.updatedAt = Date.now()
  write(plans)
  return clone(plan)
}

export function deletePlan(id: string): boolean {
  const plans = read()
  const remaining = plans.filter((plan) => plan.id !== id)
  if (remaining.length === plans.length) return false
  return write(remaining)
}

/**
 * True when the device will actually keep a library. Private-mode WebViews
 * refuse writes, and the library screen should say so rather than silently
 * losing the user's plans.
 */
export function libraryIsPersistent(): boolean {
  try {
    const probe = `${STORAGE_KEY}.probe`
    localStorage.setItem(probe, '1')
    localStorage.removeItem(probe)
    return true
  } catch {
    return false
  }
}
